box: node:6.9.1

build:
  steps:
    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

deploy:
  steps:
    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

    - script:
        name: setup git
        code: |
          git config --global user.email "bot@ertrzyiks.me"
          git config --global user.name "Deploy Bot"

    - script:
        name: npm install
        code: |
          npm install --prefix blog

    - script:
        name: deploy blog
        code: |
          npm run blog:deploy
