box: node:12

build:
  steps:
    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

    - script:
        name: install dependencies
        code: |
          cd blog && npm install

    - script:
        name: test blog
        code: |
          cd blog && npm test

deploy:
  steps:
    - script:
        name: echo nodejs information
        code: |
          echo "node version $(node -v) running"
          echo "npm version $(npm -v) running"

    - script:
        name: setup git
        code: |
          git config --global user.email "bot@ertrzyiks.me"
          git config --global user.name "Deploy Bot"

    - script:
        name: npm install
        code: |
          cd blog && npm install

    - add-to-known_hosts:
        hostname: ertrzyiks.me

    - add-ssh-key:
        keyname: DOKKU_DEPLOY

    - script:
        name: deploy blog
        code: |
          cd blog && npm run deploy
