#!/usr/bin/env bash
#
# backup-certs-accounts.sh
#
# Pulls every app's letsencrypt/ folder (ACME account keys, certificates,
# and chain files) from root@ertrzyiks.me's Dokku apps into timestamped
# snapshots under ~/Backups/dokku-letsencrypt on this Mac.
#
# Each app's data lives at $DOKKU_ROOT/<app>/letsencrypt/certs/<hash>/...
# on the remote host, where <hash> is generated by the ACME client — rather
# than hardcode a hash, this script discovers every app with a letsencrypt/
# folder and backs up that whole folder (accounts, certs, and keys) per app.
#
# Snapshots are hard-linked against the previous run (per app, via
# rsync --link-dest) so unchanged files cost no extra disk space — same
# trick Time Machine uses.
#
# Requires: passwordless SSH access to root@ertrzyiks.me (key-based auth,
# e.g. via ssh-agent or an unencrypted key referenced in ~/.ssh/config).
# This script never prompts for a password (BatchMode=yes) so it can run
# unattended; if auth isn't already keyed up, it will fail fast instead of
# hanging on a prompt.
#
# Run this locally on your Mac, not in CI or any sandbox — it needs real SSH
# access to the production host and writes its output to your home directory.
#
# Usage:
#   ./backup-certs-accounts.sh
#
# Exit codes:
#   0  success (every discovered app backed up)
#   1  remote unreachable, or no letsencrypt/ directories found
#   2  rsync failed for at least one app
#
set -euo pipefail

REMOTE_HOST="root@ertrzyiks.me"
DOKKU_ROOT="/home/dokku"

DEST_ROOT="$HOME/Backups/dokku-letsencrypt"
TIMESTAMP="$(date +%Y-%m-%d_%H%M%S)"
DEST="$DEST_ROOT/$TIMESTAMP"
LATEST_LINK="$DEST_ROOT/latest"
LOG_DIR="$DEST_ROOT/.logs"
LOG_FILE="$LOG_DIR/$TIMESTAMP.log"

SSH_OPTS=(-o BatchMode=yes -o ConnectTimeout=10)

log() {
  echo "[$(date +%H:%M:%S)] $*" | tee -a "$LOG_FILE"
}

if ! command -v rsync >/dev/null 2>&1; then
  echo "Error: rsync is not installed or not on PATH." >&2
  exit 2
fi

if ! ssh "${SSH_OPTS[@]}" "$REMOTE_HOST" "test -d '$DOKKU_ROOT'" 2>/dev/null; then
  echo "Error: cannot reach '$DOKKU_ROOT' on $REMOTE_HOST via SSH (check connectivity/auth)." >&2
  exit 1
fi

# Discover every app with a letsencrypt/ folder: $DOKKU_ROOT/<app>/letsencrypt
mapfile -t LE_DIRS < <(ssh "${SSH_OPTS[@]}" "$REMOTE_HOST" \
  "find '$DOKKU_ROOT' -mindepth 2 -maxdepth 2 -type d -name letsencrypt" 2>/dev/null)

if [[ ${#LE_DIRS[@]} -eq 0 ]]; then
  echo "Error: no letsencrypt/ directories found under '$DOKKU_ROOT' on $REMOTE_HOST." >&2
  exit 1
fi

mkdir -p "$DEST_ROOT" "$LOG_DIR"
log "Found ${#LE_DIRS[@]} app(s) with a letsencrypt/ folder"

FAILED=0
for le_dir in "${LE_DIRS[@]}"; do
  app="$(basename "$(dirname "$le_dir")")"
  app_dest="$DEST/$app/letsencrypt"
  mkdir -p "$app_dest"

  RSYNC_ARGS=(
    -a               # archive: preserves perms, timestamps, symlinks, etc.
    --delete         # snapshot reflects exactly what's on the remote right now
    --human-readable
    --stats
    -e "ssh ${SSH_OPTS[*]}"
  )
  # Hard-link against this app's previous snapshot (if any) so unchanged
  # files cost no extra disk space in this snapshot.
  if [[ -e "$LATEST_LINK/$app/letsencrypt" ]]; then
    RSYNC_ARGS+=(--link-dest="$LATEST_LINK/$app/letsencrypt")
  fi

  log "Backing up '$app' ($REMOTE_HOST:$le_dir) -> '$app_dest'"
  if rsync "${RSYNC_ARGS[@]}" "$REMOTE_HOST:$le_dir"/ "$app_dest"/ >>"$LOG_FILE" 2>&1; then
    log "  ok: $app"
  else
    log "  FAILED: $app — see $LOG_FILE for details"
    FAILED=1
  fi
done

if [[ $FAILED -eq 0 ]]; then
  # Repoint 'latest' at the snapshot we just made, for the next run's
  # --link-dest and for quick access to the newest backup.
  ln -sfn "$DEST" "$LATEST_LINK"
  log "Backup complete: $DEST"
else
  log "One or more apps failed to back up; 'latest' left pointing at the prior successful snapshot"
fi

log "Log saved to: $LOG_FILE"
exit $((FAILED == 0 ? 0 : 2))
