filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/blog-access.log
  fields:
    host: blog.ertrzyiks.me

output.logstash:
  hosts: ["stats.ertrzyiks.me:5044"]

logging:
  level: debug
