name: PR CI

on:
  pull_request:
    branches:
      - master

jobs:
  build_blog:
    name: Build Blog
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v6.0.10
        with:
          version: 11.20.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v6.1.0
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        working-directory: ./apps/blog

  build_home:
    name: Build Home
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v6.0.10
        with:
          version: 11.20.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v6.1.0
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test
        working-directory: ./apps/home

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps chromium
        working-directory: ./apps/home

      - name: Test (interaction)
        run: pnpm test:e2e
        working-directory: ./apps/home

      - name: Build
        run: pnpm build
        working-directory: ./apps/home

  build_task_manager:
    name: Build Task Manager
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v6.0.10
        with:
          version: 11.20.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v6.1.0
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test
        working-directory: ./apps/task-manager

      - name: Build
        run: pnpm build
        working-directory: ./apps/task-manager

  build_personal_assistant:
    name: Build Personal Assistant
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v6.0.10
        with:
          version: 11.20.0
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v6.1.0
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test
        working-directory: ./apps/personal-assistant

      - name: Build
        run: pnpm build
        working-directory: ./apps/personal-assistant
