name: Preview Home Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  destroy_preview:
    name: Destroy Home Preview
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.DOKKU_DEPLOY_KEY }}

      - run: echo '167.71.190.115 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEYg+BGxM8IdEoQ8fx7aDoclC0eNXSpI6l/QkLRMF/cvjJcSCk4kz/4LEkSU8eXFawp8IX/yNOyV11sJZtCVBCs=' >> ~/.ssh/known_hosts

      - name: Destroy preview app
        run: |
          ssh dokku@167.71.190.115 apps:destroy home-pr-${{ github.event.pull_request.number }} --force
